### ISSUE TITLE
Wallet is loaded but "No wallet could be found" error is shown

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisCore#34] opened 2018-03-14 23:05 UTC
Sometimes when I open the wallet, type the password and hit enter I'd get this error. After pressing "ok" I'd go to the main screen and everything is normal. 

On this screenshot you can see wallet loaded in the background and an error message on the foreground. 

![err](https://user-images.githubusercontent.com/10259355/37435646-26e8f49a-27f5-11e8-8a6a-adf4fde88519.png)

**Comment by dev0tion** [comment] 2018-03-27 10:30
Hey @noescape00, any steps to reproduce this?
I'm unable to reproduce it.

**Comment by noescape00** [comment] 2018-03-27 10:53
No, I was getting this error pretty much randomly, not sure how to reproduce it.

**Comment by noescape00** [comment] 2018-04-11 11:12
![untitled](https://user-images.githubusercontent.com/10259355/38613337-4a8ba6a6-3d92-11e8-81b3-6796a19c34b8.png)

It happened to me again on beta

ps
Can't reopen since I don't have rights for this repo

**Comment by dev0tion** [comment] 2018-10-18 19:05
@noescape00 any way to reproduce this?

**Comment by bokobza** [comment] 2018-10-18 20:46
I don't think so. Maybe let's keep it open and monitor it.

**Comment by bokobza** [comment] 2018-11-13 10:13
I'm gonna close this.

**Closed by bokobza** 2018-11-13 10:13 UTC
Labels: bug
